name: ci
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: COLOR=1 ./ci/ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  nofixups:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: COLOR=1 ./bin/nofixups.sh
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
